title: "vtt.bzh"
lang: "fr"
local: "fr_FR"
description: "Calendrier des randonnées VTT de Bretagne | VTT.bzh. Morbihan, finistère, Ille et Vilaine, Cotes d'armor, Loire Atlantique, programmer des maintenant votre prochaine rando VTT du week-end."
logo: "/assets/images/logo.png"
url: "https://www.vtt.bzh"

webmaster_verifications:
  google: "p6n7BrHhMIgg3KX7bCmj6fzgSvSRwlppzRWJY4-d9IY"
  bing:
  yandex:
  baidu:
  facebook:

author:
  name: "Nicolas Jouanno"
  contact: "mailto:nicolas@vtt.bzh"
  handle: "@byNicolasJD"
  profile_url: "https://www.nicolasjouanno.com/?utm_source=vtt-bzh&utm_medium=tool&utm_campaign=signature"

supabase:
  submit_event_url: "https://lbqjpwsifmmzxafkbcvz.supabase.co/functions/v1/submit-event"

# Output
permalink: /:title:output_ext

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
