name: Run vtt-bzh-calendar job

on:
  schedule: 
    - cron: "0 2 * * *"

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-20.04
    environment: calendar-sls
    strategy:
      matrix:
        node-version: [18]
    steps:
    - name: Only on main
      run: echo "This step will be skipped on Monday and Wednesday"
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: create env file
      run: |
        cd apps/calendar/job
        touch .env
        echo MONGO_URL=${{secrets.MONGO_URL}} >> .env
        echo CRON_START_URI=${{secrets.CRON_START_URI}} >> .env
        echo BASE_URL=${{secrets.BASE_URL}} >> .env
        echo ADMIN_NAME=${{secrets.ADMIN_NAME}} >> .env
        echo ADMIN_PASSWORD=${{secrets.ADMIN_PASSWORD}} >> .env

    - name: run job
      run: pnpm start

