name: Deploy vtt-bzh-calendar-sls on aws

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      MONGO_URL: ${{secrets.MONGO_URL}}
      CRON_START_URI: ${{secrets.CRON_START_URI}}
      BASE_URL: ${{secrets.BASE_URL}}
      ADMIN_NAME: ${{secrets.ADMIN_NAME}}
      ADMIN_PASSWORD: ${{secrets.ADMIN_PASSWORD}}
    strategy:
      matrix:
        node-version: [16]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    # - name: Install serverless
    #   run: pnpm install -g serverless@3

    - name: Deploy
      if: github.ref == 'refs/heads/main'
      run: cd services/vtt-bzh-calendar-sls && touch .env && pnpx serverless deploy --verbose