# name: Deploy vtt-bzh-calendar-sls on aws

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-20.04
#     environment: deploy
#     strategy:
#       matrix:
#         node-version: [16]
#     steps:
#     - uses: actions/checkout@v3
#     - uses: pnpm/action-setup@v2
#       with:
#         version: 7
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'pnpm'

#     - name: Install dependencies
#       run: pnpm install

#     - name: create env file
#       run: |
#         cd services/vtt-bzh-calendar-sls
#         touch .env
#         echo MONGO_URL=${{secrets.MONGO_URL}} >> .env
#         echo CRON_START_URI=${{secrets.CRON_START_URI}} >> .env
#         echo BASE_URL=${{secrets.BASE_URL}} >> .env
#         echo ADMIN_NAME=${{secrets.ADMIN_NAME}} >> .env
#         echo ADMIN_PASSWORD=${{secrets.ADMIN_PASSWORD}} >> .env

#     - name: Deploy lambda
#       if: github.ref == 'refs/heads/main'
#       env:
#         AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
#         AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
#       uses: serverless/github-action@v3.1
#       with:
#         args: -c "cd ./services/vtt-bzh-calendar-sls && serverless deploy --stage production"
#         entrypoint: /bin/sh
