name: Build and deploy site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_run:
    workflows: ["Run vtt-bzh-calendar job"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    if: github.event_name == 'push' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-24.04
    environment: github-pages
    strategy:
      matrix:
        node-version: [24]
    steps:
      - uses: actions/checkout@v3
      - name: Use ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0.2'
          bundler-cache: true
      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install node dependencies
        run: pnpm install
      - name: Install ruby dependencies
        run: pnpm --filter=www install:jekyll
      - name: Generate events
        run: pnpm --filter=jobs run generate-events
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_TABLE: ${{ secrets.SUPABASE_TABLE }}
      - name: Build
        run: pnpm build
      - name: Lint
        run: pnpm lint
      #- name: Test
      #  run: pnpm test
      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: www.vtt.bzh
