name: Run vtt-bzh-calendar job

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  run:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-24.04
    environment: cron
    strategy:
      matrix:
        node-version: [24]
    steps:
      - name: Only on main
        run: echo "This step will be skipped on Monday and Wednesday"
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: run job
        run: pnpm job
        env:
          CRON_START_URI: ${{ secrets.CRON_START_URI }}
          WUFOO_USERNAME: ${{ secrets.WUFOO_USERNAME }}
          WUFOO_PASSWORD: ${{ secrets.WUFOO_PASSWORD }}
          WUFOO_DOMAIN: ${{ secrets.WUFOO_DOMAIN }}
          WUFOO_FORM: ${{ secrets.WUFOO_FORM }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_TABLE: ${{ secrets.SUPABASE_TABLE }}
